version: 0.2

env:
  variables:
    ECR_REPOSITORY: '671939990958.dkr.ecr.ap-south-1.amazonaws.com/cd-demo'
    COMMIT_HASH: 'latest'

phases:
  install:
    commands:
      - echo listing -----
      - ls $CODEBUILD_SRC_DIR_MetadataArtifects
      - echo Installing project dependencies...
      - npm install
      - echo Reading metadata from the metadataOutput file...
      - for key in $(jq -r 'keys[]' $METADATA_FILE); do export $key=$(jq -r ".${key}" $METADATA_FILE); done
      - echo MicroserviceA Version- $MicroserviceA # This should print the version for MicroserviceA
      - env
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY
      - echo Pulling the latest Docker image...
      - docker-compose pull
  build:
    commands:
      - echo Build started on `date`
      - echo Running Docker containers...
      - docker-compose up -d
      - echo Running acceptance tests...
      - npm run test:acceptance
