version: '3'
services:
  app:
    image: 671939990958.dkr.ecr.ap-south-1.amazonaws.com/cd-demo:${COMMIT_HASH}
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=acceptance-test  # or development, test, etc.
  # Uncomment below when you add a database
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: youruser
  #     POSTGRES_PASSWORD: yourpassword
